
# This is a basic workflow to help you get started with Actions

name: Docker Container Build & Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Log in to the registry
      - name: Docker login
        run: |
          docker login ghcr.io --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}
      # Build the image
      - name: Docker build
        run: |
          docker build . -t ghcr.io/teknowafel/tugboat:latest
      # Push the image
      - name: Docker push
        run: |
          docker push ghcr.io/teknowafel/tugboat:latest